require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'app' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'appTests' do
    inherit! :complete
    # Pods for testing
  end


end

