#target 'MyApp' do
#  pod 'AFNetworking', '~> 2.6'

#pod 'ORStackView', '~> 3.0'
#  pod 'SwiftyJSON', '~> 2.3'
#end

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking', '~> 2.6'
  # Pods for app

  target 'appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'app-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for app-tvOS

  target 'app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
